bank =
  title: 'How about this shit?'

  adjectives: [
    ["Shallow", "Deep"],
    ["Dirty"],
    ["Shitty", "Poopy"],
    ["Fuckable"],
    ["Fucking"],
    ["Bearded"],
    ["Fluffy"],
    ["Fat"],
    ["Black", "Brown"],
    ["Dark"],
    ["Heavy"],
    ["Energetic"],
    ["American", "Chinese", "Russian", "Alaskan", "French"],
    ["Broken"],
    ["Curly", "Hairy"],
    ["Sapphire"],
    ["24/7"],
    ["Sexual", "Sexy", "Seductive"],
    ["Ginger"],
    ["Hot", "Cold"],
    ["Sensitve"],
    ["Occupied"]
  ]

  nouns: [
    ["Porn", "Pron"],
    ["Snow"],
    ["Cocaine", "Heroin", "PCP", "Shroom", "Acid"],
    ["Nipple", "Boob", "Tit"],
    ["Factory"],
    ["Balls"],
    ["Cleveland"],
    ["Steamer"],
    ["Blumpkin"],
    ["Pipeline"],
    ["Karl"],
    ["Scooter"],
    ["Box"],
    ["Moon"],
    ["Bear"],
    ["Beaver"],
    ["Boar"],
    ["Bull"],
    ["Bunny"],
    ["Cat", "Cougar", "Panther"],
    ["Dingo"],
    ["Donkey"],
    ["Goat"],
    ["Hamster"],
    ["Hog"],
    ["Llama"],
    ["Monkey"],
    ["Panda"],
    ["Pony"],
    ["Sheep"],
    ["Whore", "Slut", "Prostitute", "Stripper"],
    ["Woman"],
    ["Man"],
    ["Dildo"],
    ["Fuck"],
    ["Shit", "Poop"],
    ["Bastard"],
    ["Asshole", "Butthole", "Butt", "Ass", "Hole"],
    ["Shelby"],
    ["Tampon"],
    ["Dead-baby"],
    ["Toilet"],
    ["Poop"],
    ["Penis", "Dick"],
    ["Vagina"],
    ["Mouth", "Lip", "Tongue"],
    ["Sex"]
  ]

  verbs: [
    ["Fuck"],
    ["Touch"],
    ["Stick"],
    ["Finger"],
    ["Sexify"],
    ["Lick"],
    ["Massage"],
    ["Milk"],
    ["Tickle"],
    ["Blow"],
    ["Suck"],
    ["Nuzzle"],
    ["Cuddle"]
  ]

  conjunctions: [
    ["a"],
    ["the"],
    ["Her"],
    ["His"],
    ["My"],
    ["Your"],
    ["Jared's"]
  ]

module.exports = bank
