// Generated by CoffeeScript 1.6.3
(function() {
  var ADJECTIVE, ADJECTIVE_NOUN_NOUN, NOUN, NOUN_NOUN_NOUN, VERB, patternMap;

  ADJECTIVE = 0;

  VERB = 1;

  NOUN = 2;

  ADJECTIVE_NOUN_NOUN = 0;

  NOUN_NOUN_NOUN = 1;

  patternMap = {
    ADJECTIVE_NOUN_NOUN: [ADJECTIVE, NOUN, NOUN],
    NOUN_NOUN_NOUN: [NOUN, NOUN, NOUN]
  };

}).call(this);
