// Generated by CoffeeScript 1.7.1
(function() {
  var app, exphbs, express, logfmt, nsfwBank, port, rando, sfwBank;

  express = require("express");

  exphbs = require("express3-handlebars");

  logfmt = require("logfmt");

  rando = require("./rando.js");

  app = express();

  app.use(logfmt.requestLogger());

  app.use(express["static"](__dirname + "/../public"));

  app.engine("handlebars", exphbs());

  app.set("view engine", "handlebars");

  nsfwBank = require("./banks/nsfw.js");

  sfwBank = require("./banks/sfw.js");

  app.get("/", (function(_this) {
    return function(req, res) {
      var bank, generator, nsfw, sprintName;
      nsfw = req.query.nsfw === "yes";
      bank = nsfw ? nsfwBank : sfwBank;
      generator = rando();
      sprintName = generator.randomSprintName(bank, req.query.pattern);
      if (req.query.format === "json") {
        return res.json({
          sprintName: sprintName
        });
      } else {
        return res.render("index", {
          sprintName: sprintName,
          nsfw: nsfw
        });
      }
    };
  })(this));

  port = process.env.PORT || 5000;

  app.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
