// Generated by CoffeeScript 1.10.0
(function() {
  var app, banks, exphbs, express, logfmt, mjBank, nsfwBank, port, rando, sfwBank;

  express = require('express');

  exphbs = require('express3-handlebars');

  logfmt = require('logfmt');

  rando = require('./rando.js');

  app = express();

  app.use(logfmt.requestLogger());

  app.use(express["static"](__dirname + '/../public'));

  app.engine('handlebars', exphbs());

  app.set('view engine', 'handlebars');

  nsfwBank = require('./banks/nsfw.js');

  sfwBank = require('./banks/sfw.js');

  mjBank = require('./banks/mj.js');

  banks = {
    sfw: sfwBank,
    nsfw: nsfwBank,
    mj: mjBank
  };

  app.get('/', (function(_this) {
    return function(req, res) {
      var bank, bankName, generator, sprintName;
      bankName = req.query.bank || 'sfw';
      bank = banks[bankName] || sfwBank;
      generator = rando();
      sprintName = generator.randomSprintName(bank, req.query.pattern);
      if (req.query.format === 'json') {
        return res.json({
          sprintName: sprintName
        });
      } else {
        return res.render('index', {
          sprintName: sprintName,
          nsfw: bankName === 'nsfw'
        });
      }
    };
  })(this));

  port = process.env.PORT || 5000;

  app.listen(port, function() {
    return console.log('Listening on ' + port);
  });

}).call(this);
