// Generated by CoffeeScript 1.6.3
(function() {
  var app, exphbs, express, logfmt, port, rando,
    _this = this;

  express = require("express");

  exphbs = require("express3-handlebars");

  logfmt = require("logfmt");

  rando = require("./rando.js");

  app = express();

  app.use(logfmt.requestLogger());

  app.use(express["static"](__dirname + "/../public"));

  app.engine("handlebars", exphbs());

  app.set("view engine", "handlebars");

  app.get("/", function(req, res) {
    return res.render("index", {
      sprintName: rando.randomSprintName()
    });
  });

  port = process.env.PORT || 5000;

  app.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
