// Generated by CoffeeScript 1.10.0
(function() {
  var bank;

  bank = {
    title: 'Your cannabis shop name is',
    adjectives: [['Friendly'], ['Green', 'Emerald'], ['Pacific'], ['Legal'], ['Serene'], ['Holistic'], ['Northwest', 'West', 'West Coast'], ['Lucky'], ['Natural'], ['Dank'], ['Evergreen'], ['Organic'], ['High', 'HI', 'Low'], ['Medical', 'Recreational'], ['International'], ['Local'], ['Seattle', 'Denver', 'Spokane'], ['Cronic'], ['7', '21', '11', '9', '1'], ['420', '4:20'], ['Paper'], ['Kush']],
    nouns: [['Solutions'], ['Bud', 'Buds'], ['Leaf', 'Leaves'], ['Greens'], ['Greenery'], ['Cannabis'], ['Marijuana'], ['MJ'], ['Pot'], ['Ganja'], ['Weed'], ['Grass'], ['Reefer'], ['Shop', 'Market', 'Boutique'], ['Herb', 'Herbs'], ['Company'], ['Wellness'], ['Trees', 'Tree'], ['Joint'], ['Bong', 'Pipe', 'Paraphernalia', 'Glass'], ['Garden'], ['Organics'], ['Reefer'], ['Street'], ['Grade'], ['Collective'], ['Haze'], ['Den'], ['Stuff']],
    verbs: [],
    conjunctions: [['the'], ['a']]
  };

  module.exports = bank;

}).call(this);
