// Generated by CoffeeScript 1.6.3
(function() {
  var bank;

  bank = {
    adjectives: ["Shitty", "Fuckable", "Fucking", "Bearded", "Fluffy", "Fat", "Black", "Deep", "Dark", "Heavy", "Energetic", "American", "Chinese", "Russian", "French", "Brown", "Poopy", "Broken", "Curly", "Hairy", "Sapphire", "24/7", "Sexual", "Sexy", "Seductive", "Ginger"],
    nouns: ["Ass", "Bear", "Beaver", "Boar", "Bull", "Bunny", "Cat", "Cougar", "Dingo", "Donkey", "Goat", "Hamster", "Hog", "Llama", "Monkey", "Panda", "Panther", "Pony", "Sheep", "Whore", "Woman", "Man", "Dildo", "Fuck", "Shit", "Bastard", "Asshole", "Shelby", "Slut", "Tampon", "Dead-baby", "Butthole", "Hole", "Toilet", "Poop", "Penis", "Vagina", "Dick", "Mouth", "Lip", "Sex", "Prostitute", "Stripper"],
    verbs: ["Fuck", "Touch", "Stick", "Finger", "Sexify", "Lick", "Massage", "Milk", "Tickle"],
    conjunctions: ["a", "the", "Her", "His", "My", "Your", "Jared's"]
  };

  module.exports = bank;

}).call(this);
